In [1]:
import pandas as pd
import json,random

In [2]:
df = pd.read_csv("../../data/processed/TrainingData/marriage_data_india.csv")
df.head(5)

Age_at_Marriage  Gender Education_Level Caste_Match Religion Urban_Rural  \
0               23    Male        Graduate   Different    Hindu       Urban   
1               28  Female          School        Same    Hindu       Rural   
2               39    Male    Postgraduate        Same   Muslim       Rural   
3               26  Female          School   Different    Hindu       Urban   
4               32  Female        Graduate        Same    Hindu       Rural   

  Income_Level Spouse_Working Inter-Caste Inter-Religion      target  
0       Middle             No          No             No  Medium_Yes  
1       Middle             No          No            Yes      Low_No  
2         High             No          No             No   Medium_No  
3         High             No         Yes             No      Low_No  
4       Middle             No          No            Yes   Medium_No

Age,gender,eduction_level(degrees),caste,Income(salary LPA) these are the features that are observed in the 
Advertisement for bride or groom

In [3]:
for i in df.columns:
    print(f"\n {i}")
    print(df[i].dtype)
    print(df[i].unique())

print(df["Income_Level"].unique())


 Age_at_Marriage
int64
[23 28 39 26 32 37 24 18 22 19 31 34 20 27 35 36 21 29 30 25 33 38]

 Gender
object
['Male' 'Female']

 Education_Level
object
['Graduate' 'School' 'Postgraduate' 'PhD']

 Caste_Match
object
['Different' 'Same']

 Religion
object
['Hindu' 'Muslim' 'Sikh' 'Christian' 'Others']

 Urban_Rural
object
['Urban' 'Rural']

 Income_Level
object
['Middle' 'High' 'Low']

 Spouse_Working
object
['No' 'Yes']

 Inter-Caste
object
['No' 'Yes']

 Inter-Religion
object
['No' 'Yes']

 target
object
['Medium_Yes' 'Low_No' 'Medium_No' 'High_No' 'Low_Yes' 'High_Yes']
['Middle' 'High' 'Low']


In [4]:
df2 = pd.read_csv("../../data/processed/ProfileData/processed_vivah_profiles.csv")
df2.head(5)


Religion              Caste Mother Tongue           Profession  \
0    hindu            maratha       english            scientist   
1   muslim             hanafi          urdu          not working   
2    hindu  brahmin himachali         hindi          not working   
3    hindu               koli       kannada               doctor   
4    hindu             kuruba       kannada  admin/ front office   

      Education  Age  Height in cm Height_ft_in Country             State  \
0  Postgraduate   26           162      5ft 4in   india       maharashtra   
1      Graduate   21           154      5ft 1in   india         telangana   
2      Graduate   35           162      5ft 4in   india  himachal pradesh   
3  Postgraduate   30           162      5ft 4in   india         karnataka   
4      Graduate   30           162      5ft 4in   india         karnataka   

          City  Gender Income Independency  Previous Marriage Addiction  
0  navi mumbai  Female   High          Low                  0        No  
1    hyderabad  Female    Low          Low                  0        No  
2       shimla  Female    Low       Medium                  0        No  
3        bidar  Female   High         High                  0       Yes  
4    bangalore  Female    Low       Medium                  0        No

In [5]:
for col in df2.columns:
    print(f"\n{col}")
    print(df2[col].unique())


Religion
['hindu' 'muslim' 'buddhist']

Caste
['maratha' 'hanafi' 'brahmin himachali' 'koli' 'kuruba' 'brahmin'
 'buddhist' 'rajput' 'vishwakarma' 'brahmin gour']

Mother Tongue
['english' 'urdu' 'hindi' 'kannada' 'punjabi' 'marathi' 'kumoani'
 'bhojpuri']

Profession
['scientist' 'not working' 'doctor' 'admin/ front office' 'other'
 'consultant' 'chartered accountant']

Education
['Postgraduate' 'Graduate' 'School' 'Other']

Age
[26 21 35 30 33 32 22]

Height in cm
[162 154 152 157 132]

Height_ft_in
['5ft 4in' '5ft 1in' '5ft 0in' '5ft 2in' '4ft 4in']

Country
['india']

State
['maharashtra' 'telangana' 'himachal pradesh' 'karnataka' 'delhi'
 'uttar pradesh' 'jharkhand' 'odisha']

City
['navi mumbai' 'hyderabad' 'shimla' 'bidar' 'bangalore' 'new delhi'
 'wardha' 'greater noida' 'jamshedpur' 'cuttack']

Gender
['Female' 'Male']

Income
['High' 'Low']

Independency
['Low' 'Medium' 'High']

Previous Marriage
[0 1]

Addiction
['No' 'Yes']


General: General Brahmin, General, Kayastha, Baisya, Banerjee, Mukherjee, Roy, Biswas, Chatterjee, Dutta, Banik, Ganguly, Bhattacharya, Aguri, Tili

OBC: Tili, Kumbhakar, Swarnakar, Napit, Goala, Barujibi, Malakar, Sadgop, Tambuli

SC: Namasudra

Muslim (OBC eligible): Sunni

In [6]:
# List of castes
castes = {
    "Brahmin": 10,
    "SC": 5,
    "OBC": 5,
    "Baisya": 3.1,
    "Kayastha": 10,
    "Banerjee": 0.1,
    "General": 5,
    "Tili": 0.5,
    "Barujibi": 0.1,
    "Kumbhakar": 0.2,
    "Swarnakar": 1,
    "Napit": 0.1,
    "Namasudra": 0.1,
    "Sunni": 2.5,
    "Sadgop": 0.1,
    "Goala": 0.1,
    "Kandi": 0.1,
    "Tambuli": 0.1,
    "Mukherjee": 0.1,
    "Roy": 0.1,
    "Biswas": 0.2,
    "Chatterjee": 0.2,
    "Dutta": 0.1,
    "Banik": 0.1,
    "Ganguly": 0.1,
    "Bhattacharya": 0.1,
    "Aguri": 0.01,
    "Malakar": 0.01,
    "Yadav": 0.01
}

def select_caste_by_weight():
    caste = list(castes.keys())
    freq = list(castes.values())
    return random.choices(caste, weights=freq, k=1)[0]


School-Class VIII
Graduate-Bcom, BSc, BA, BA Ed, Btech, LLB
Postgraduate-MA, B.Ed, MBA, Masters, LLM, MSC B Ed, MDS
PhD-PhD

In [7]:
degrees = {
    'B.Tech MBA':2,
    'MBA':6,
    'B.Tech':5,
    'BSc': 2,
    'BA': 6,
    'MA B.Ed': 4,
    'MA':6,
    'MSC B.Ed': 5,
    'BA B.Ed': 1,
    'PhD':1,
    'Bcom':0.5,
    'LLB': 1,
    'LLM': 0.5
}
def select_degree_by_weight():
    degree = list(degrees.keys())
    freq = list(degrees.values())
    return random.choices(degree, weights=freq, k=1)[0]

Low: Hospital Nurse, Advocate, College lecturer
Middle: 12LPA, 15LPA, MNC-IT, IT, Digital Marketing B'lore, Bank, Business, Pharma Co B'loe, Law Firm
High: 20LPA, Research-Scholar-Germany, Law Firm

In [8]:
salaries_preofessions ={
    '20LPA': 1,
    '12LPA': 1,
    '15LPA': 1,
    'MNC-IT': 4,
    'IT': 4,
    'Researcg-Scholar-germany': 1,
    'Business': 4,
    'Bank': 2,
    'Pharma Co B\'loe': 1,
    'Law Firm': 1,
    'Hospital Nurse': 1,
    'Advocate': 1,
    'College lecturer': 1,
    'Digital Marketting B\'lore': 1,
} 
def slect_profession_by_weight():
    salaries_preofession = list(salaries_preofessions.keys())
    freq = list(salaries_preofessions.values())
    return random.choices(salaries_preofession, weights=freq, k=1)[0]

In [9]:
age = [
    23, 28, 39, 26, 32, 37, 24, 18, 22, 19, 31, 34, 20, 27, 35, 
    36, 21, 29, 30, 25, 33, 38
]
heights = [162, 154, 152, 157, 132]

In [35]:
sum = df["Religion"].value_counts().sum()
religion_weights = dict(df["Religion"].value_counts().apply(lambda x : x/sum))

print(religion_weights)

{'Hindu': np.float64(0.6034), 'Muslim': np.float64(0.1939), 'Christian': np.float64(0.099), 'Others': np.float64(0.0531), 'Sikh': np.float64(0.0506)}


Age,gender,eduction_level(degrees),caste,Income(salary LPA) these are the features that are observed in the 
Advertisement for bride or groom

In [52]:
df["UserID"] = [f"U{i:03d}" for i in range(len(df))]
df.set_index("UserID", inplace=True) 

user_profile= {
    "Age": df["Age_at_Marriage"],
    "Genedr": df["Gender"],
    "Education": [select_degree_by_weight() for _ in range(len(df))],
    "Caste": [select_caste_by_weight() for _ in range(len(df))],
    "Profession": [slect_profession_by_weight() for _ in range(len(df))],
    "Religion": [random.choices(
                    population=list(religion_weights.keys()),
                    weights=list(religion_weights.values()))[0] for _ in range(len(df))],
    "residence": random.choice(['urban','rural']),
    "Height_cm": random.choice(heights),
    "Extras": df.apply(
        lambda x: json.dumps({
            "Urban_Rural": x["Urban_Rural"],
            "Spouse_Working": x["Spouse_Working"]
        }),
        axis=1
    )
}
user_profile_df = pd.DataFrame(user_profile)
user_profile_df.head(5)


Age  Genedr Education     Caste Profession Religion residence  \
UserID                                                                  
U000     23    Male        BA  Kayastha   Business    Hindu     urban   
U001     28  Female        BA  Kayastha       Bank   Muslim     urban   
U002     39    Male       LLB   Brahmin       Bank    Hindu     urban   
U003     26  Female        BA    Baisya     MNC-IT    Hindu     urban   
U004     32  Female        MA  Kayastha       Bank    Hindu     urban   

        Height_cm                                            Extras  
UserID                                                               
U000          154  {"Urban_Rural": "Urban", "Spouse_Working": "No"}  
U001          154  {"Urban_Rural": "Rural", "Spouse_Working": "No"}  
U002          154  {"Urban_Rural": "Rural", "Spouse_Working": "No"}  
U003          154  {"Urban_Rural": "Urban", "Spouse_Working": "No"}  
U004          154  {"Urban_Rural": "Rural", "Spouse_Working": "No"}

In [55]:
user_profile_df.loc['U001',"Caste"]

'Kayastha'

In [42]:
def assign_preferred_cast(row):
    if row["Caste_Match"] == "Same":
        return user_profile_df.loc[row.name, "Caste"]
    else:
        return select_caste_by_weight()

In [56]:
def assign_preferred_religion(row):
    if row["Inter-Religion"] == "No":
        print(row.name)
        return user_profile_df.loc[row.name, "Religion"]
    else:
        return random.choices(
            population=list(religion_weights.keys()),
            weights=list(religion_weights.values())
        )[0]

In [44]:
sum = df["Age_at_Marriage"].value_counts().sum()
age_weights = dict(df["Age_at_Marriage"].value_counts().apply(lambda x : x/sum))

print(age_weights)

{31: np.float64(0.0488), 26: np.float64(0.0487), 29: np.float64(0.0484), 27: np.float64(0.0479), 22: np.float64(0.0476), 28: np.float64(0.0471), 34: np.float64(0.047), 30: np.float64(0.0465), 19: np.float64(0.0462), 20: np.float64(0.046), 35: np.float64(0.046), 37: np.float64(0.0455), 32: np.float64(0.0455), 36: np.float64(0.0448), 33: np.float64(0.0441), 21: np.float64(0.0438), 38: np.float64(0.0437), 24: np.float64(0.0433), 18: np.float64(0.043), 39: np.float64(0.0422), 25: np.float64(0.0422), 23: np.float64(0.0417)}


In [49]:
gender = df["Gender"].apply(lambda x: "Female" if x == "Male" else "Male")

In [58]:
user_preference_df = pd.DataFrame(index=df.index)
user_preference_df["Age"] = [random.choices(population=list(age_weights.keys()),
                                             weights=list(age_weights.values()))[0] 
                             for _ in range(len(df))]
user_preference_df["Gender"] = gender
user_preference_df["Education"] = [select_degree_by_weight() for _ in range(len(df))]
user_preference_df["Caste"] = [
    user_profile_df.loc[i, "Caste"] if df.loc[i, "Caste_Match"]=="Same" else select_caste_by_weight()
    for i in df.index
]
user_preference_df["Profession"] = [slect_profession_by_weight() for _ in range(len(df))]
user_preference_df["Residence"] = [random.choice(['urban','rural']) for _ in range(len(df))]
user_preference_df["Religion"] = [
    user_profile_df.loc[i, "Religion"] if df.loc[i, "Inter-Religion"]=="No" else
    random.choices(population=list(religion_weights.keys()), weights=list(religion_weights.values()))[0]
    for i in df.index
]
user_preference_df["Height_cm"] = [random.choice(heights) for _ in range(len(df))]
user_preference_df["Extras"] = df.apply(
    lambda x: json.dumps({
        "Urban_Rural": x["Urban_Rural"],
        "Spouse_Working": x["Spouse_Working"]
    }),
    axis=1
)

user_preference_df.head(5)

Age  Gender   Education     Caste Profession Residence   Religion  \
UserID                                                                      
U000     36  Female         LLB  Kayastha      20LPA     urban      Hindu   
U001     19    Male          MA  Kayastha      20LPA     urban  Christian   
U002     21  Female  B.Tech MBA   Brahmin      20LPA     rural      Hindu   
U003     18    Male          MA  Kayastha   Business     urban      Hindu   
U004     38    Male     MA B.Ed  Kayastha   Business     urban     Muslim   

        Height_cm                                            Extras  
UserID                                                               
U000          132  {"Urban_Rural": "Urban", "Spouse_Working": "No"}  
U001          154  {"Urban_Rural": "Rural", "Spouse_Working": "No"}  
U002          152  {"Urban_Rural": "Rural", "Spouse_Working": "No"}  
U003          132  {"Urban_Rural": "Urban", "Spouse_Working": "No"}  
U004          157  {"Urban_Rural": "Rural", "Spouse_Working": "No"}

In [60]:
user_profile_df.to_csv("user_profiles.csv")
user_preference_df.to_csv("user_preferences.csv")

In [26]:
for i in df.columns:
    print(f"\n {i}")
    print(df[i].dtype)
    print(df[i].unique())

df.head(5)


 Age_at_Marriage
int64
[23 28 39 26 32 37 24 18 22 19 31 34 20 27 35 36 21 29 30 25 33 38]

 Gender
object
['Male' 'Female']

 Education_Level
object
['Graduate' 'School' 'Postgraduate' 'PhD']

 Caste_Match
object
['Different' 'Same']

 Religion
object
['Hindu' 'Muslim' 'Sikh' 'Christian' 'Others']

 Urban_Rural
object
['Urban' 'Rural']

 Income_Level
object
['Middle' 'High' 'Low']

 Spouse_Working
object
['No' 'Yes']

 Inter-Caste
object
['No' 'Yes']

 Inter-Religion
object
['No' 'Yes']

 target
object
['Medium_Yes' 'Low_No' 'Medium_No' 'High_No' 'Low_Yes' 'High_Yes']


Age_at_Marriage  Gender Education_Level Caste_Match Religion  \
UserID                                                                 
U000                 23    Male        Graduate   Different    Hindu   
U001                 28  Female          School        Same    Hindu   
U002                 39    Male    Postgraduate        Same   Muslim   
U003                 26  Female          School   Different    Hindu   
U004                 32  Female        Graduate        Same    Hindu   

       Urban_Rural Income_Level Spouse_Working Inter-Caste Inter-Religion  \
UserID                                                                      
U000         Urban       Middle             No          No             No   
U001         Rural       Middle             No          No            Yes   
U002         Rural         High             No          No             No   
U003         Urban         High             No         Yes             No   
U004         Rural       Middle             No          No            Yes   

            target  
UserID              
U000    Medium_Yes  
U001        Low_No  
U002     Medium_No  
U003        Low_No  
U004     Medium_No